# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# https://www.asensar.com/guide/arduino_atemlstudio/program-arduino-with-avrdude.html

ARDMK_DIR = /usr/local/opt/arduino-mk
BOARD_TAG = uno
AVRDUDE = /usr/local/bin/avrdude
MONITOR_BAUDRATE  = 9600
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE = /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude
AVRDUDE_CONF = /Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf

### Do not touch - the path to Arduino.mk, inside the ARDMK_DIR
include $(ARDMK_DIR)/Arduino.mk